apiVersion: v1
kind: Secret
metadata:
  name: mongodb-exporter-secret
  namespace: mymicroservices
type: Opaque
stringData:
  datasource: "mongodb://mongodb_exporter:mongodb@mongodb-server-svc:27017/admin?ssl=false"
  MONGO_EXPORTER_USER: mongodb_exporter
  MONGO_EXPORTER_PASSWORD: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter-dpl
  namespace: mymicroservices
  labels:
    app: mongo-exporter-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exporter
  template:
    metadata:
      name: mongo-exporter
      labels:
        app: mongo-exporter
    spec:
      containers:
        - name: mongo-exporter
          image: bitnami/mongodb-exporter
          imagePullPolicy: IfNotPresent
          args:
            - --discovering-mode
            - --compatible-mode
            - --mongodb.direct-connect=false
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-exporter-secret
                  key: datasource
          ports:
            - name: metric-port
              containerPort: 9216
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exporter-svc
  namespace: mymicroservices
  labels:
    app: mongo-exporter-svc
spec:
  selector:
      app: mongo-exporter
  ports:
  - name: mongo-exporter
    protocol: TCP
    port: 9216
    targetPort: 9216