apiVersion: v1
kind: Secret
metadata:
  name: mailhog-secret
  namespace: mymicroservices
type: Opaque
stringData:  
  SMTP_SERVER_USER: ""
  SMTP_SERVER_PASSWORD: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mailhog-dpl
 namespace: mymicroservices
 labels:
    app: mailhog-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      name: mailhog
      labels:
        app: mailhog
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: mailhog
          image: mailhog/mailhog:latest
          ports:
            - name: smtp
              containerPort: 1025
            - name: web
              containerPort: 8025
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 1000m          
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-web-svc
  namespace: mymicroservices
  labels:
    app: mailhog-web-svc
    primary: 'true'
spec:
  selector:
    app: mailhog
  ports:
    - name: web
      protocol: TCP
      port: 8025
      targetPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-smtp-svc
  namespace: mymicroservices
  labels:
    app: mailhog-smtp-svc
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
