apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger-dpl
    namespace: mymicroservices
    labels:
      app: jaeger-dpl
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: jaeger
    template:
      metadata:
        name: jaeger
        labels:
          app: jaeger
          app.kubernetes.io/name: jaeger
          app.kubernetes.io/component: all-in-one
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "16686"
      spec:
          containers:
          -   env:
              - name: COLLECTOR_ZIPKIN_HTTP_PORT
                value: "9411"
              - name: QUERY_BASE_PATH
                value: /jaeger
              image: jaegertracing/all-in-one
              name: jaeger
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP              
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 14269
                initialDelaySeconds: 5
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query-svc
    namespace: mymicroservices
    labels:
      app: jaeger-query-svc
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: query
  spec:
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    ports:
      - name: query-http
        protocol: TCP
        port: 16686
        targetPort: 16686
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector-svc
    namespace: mymicroservices
    labels:
      app: jaeger-collector-svc
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: collector
  spec:
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    ports:
    - name: jaeger-collector-tchannel
      protocol: TCP
      port: 14267
      targetPort: 14267
    - name: jaeger-collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: jaeger-collector-zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent-svc
    namespace: mymicroservices
    labels:
      app: jaeger-agent-svc
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
  spec:
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    ports:
    - name: agent-zipkin-thrift
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: agent-compact
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: agent-binary
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: agent-configs
      protocol: TCP
      port: 5778
      targetPort: 5778
    clusterIP: None
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin-svc
    namespace: mymicroservices
    labels:
      app: zipkin-svc
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: zipkin
  spec:
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
    ports:
    - name: jaeger-collector-zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
    clusterIP: None

