global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-microservices'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nginx_exporter'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginxexporter-svc:9113']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter-svc:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor-svc:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 10s
    static_configs:
      - targets: ['grafana-svc:3001']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway-svc:9091']

  - job_name: 'mongo-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mongo-exporter-svc:9216']

  - job_name: 'authentication'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['authentication-svc:5100']

  - job_name: 'cart'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['cart-svc:5500']

  - job_name: 'customer'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['customer-svc:5300']

  - job_name: 'email'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['email-svc:52000']
  
  - job_name: 'order'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['order-svc:5600']

  - job_name: 'payment'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['payment-svc:5700']

  - job_name: 'product'
    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['product-svc:5400']


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager-svc:9093'
#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
