apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-dpl
  namespace: mymicroservices
  labels:
    app: cart-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      name: cart
      labels:
        app: cart
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cart        
        image: joaosalazar/carts
        imagePullPolicy: Always
        env:
        - name: kubernetes
          value: "true"
        - name: PASSWORDPERMISSIONENDPOINT
          valueFrom:
            secretKeyRef:
              name: certificate-permission-secret
              key: PASSWORDPERMISSIONENDPOINT
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASSWORD
        - name: MONGO_EXPORTER_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_USER
        - name: MONGO_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_PASSWORD
        - name: PROMETHEUS_PUSHGATEWAY
          valueFrom:
            configMapKeyRef:
              name: prometheus-pushgateway-map
              key: PROMETHEUS_PUSHGATEWAY
        ports:
          - containerPort: 5500
        resources:
            requests:
              cpu: "0.125"
              memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  namespace: mymicroservices
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
    - name: http-web
      protocol: TCP
      port: 5500
      targetPort: 5500
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cart-alerts
  namespace: observability
  labels:
    release: kube-prom-stack
    role: server-rules
spec:
  groups:
  - name: cart.rules
    rules:
    - alert: cart_down
      expr: absent(container_memory_usage_bytes{container="cart"})
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: Cart down
        description: Cart container is down for more than 30 seconds.
    - alert: cart_high_cpu
      expr: sum(rate(container_cpu_usage_seconds_total{container="cart"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Cart high CPU usage
        description: Cart CPU usage is {{ humanize $value}}%.
    - alert: cart_high_memory
      expr: sum(container_memory_usage_bytes{container="cart"}) > 1200000000
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Cart high memory usage
        description: Cart memory consumption is at {{ humanize $value}}.
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-svc
  namespace: observability
  labels:
    app: cart
    release: kube-prom-stack
spec:  
  selector:
    matchLabels:
      app: cart      
  endpoints:
    - port: http-web
      interval: 15s
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:                                                                                                                                                                                                                      
    matchNames:                                                                                                                                                                                                                           
    - mymicroservices