apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pv-claim
  namespace: mymicroservices
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi