apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-dpl
  namespace: mymicroservices
  labels:
    app: order-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: order        
        image: joaosalazar/orders
        imagePullPolicy: Always
        env:
        - name: kubernetes
          value: "true"
        - name: PASSWORDPERMISSIONENDPOINT
          valueFrom:
            secretKeyRef:
              name: certificate-permission-secret
              key: PASSWORDPERMISSIONENDPOINT
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASSWORD
        - name: MONGO_EXPORTER_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_USER
        - name: MONGO_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_PASSWORD
        - name: PROMETHEUS_PUSHGATEWAY
          valueFrom:
            configMapKeyRef:
              name: prometheus-pushgateway-map
              key: PROMETHEUS_PUSHGATEWAY
        ports:
          - containerPort: 5600
        resources:
            requests:
              cpu: "0.125"
              memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: mymicroservices
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - name: http-web
      protocol: TCP
      port: 5600
      targetPort: 5600
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: order-alerts
  namespace: observability
  labels:
    release: kube-prom-stack
    role: server-rules
spec:
  groups:
  - name: order.rules
    rules:
    - alert: order_down
      expr: absent(container_memory_usage_bytes{container="order"})
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: Order down
        description: Order container is down for more than 30 seconds.
    - alert: order_high_cpu
      expr: sum(rate(container_cpu_usage_seconds_total{container="order"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Order high CPU usage
        description: Order CPU usage is {{ humanize $value}}%.
    - alert: order_high_memory
      expr: sum(container_memory_usage_bytes{container="order"}) > 1200000000
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Order high memory usage
        description: Order memory consumption is at {{ humanize $value}}.
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-svc
  namespace: observability
  labels:
    app: order
    release: kube-prom-stack
spec:  
  selector:
    matchLabels:
      app: order      
  endpoints:
    - port: http-web
      interval: 15s
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:                                                                                                                                                                                                                      
    matchNames:                                                                                                                                                                                                                           
    - mymicroservices