apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-dpl
  namespace: mymicroservices
  labels:
    app: product-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      name: product
      labels:
        app: product
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: product        
        image: joaosalazar/products
        imagePullPolicy: Always
        env:
        - name: kubernetes
          value: "true"
        - name: PASSWORDPERMISSIONENDPOINT
          valueFrom:
            secretKeyRef:
              name: certificate-permission-secret
              key: PASSWORDPERMISSIONENDPOINT
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: MONGO_EXPORTER_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_USER
        - name: MONGO_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-exporter-secret
              key: MONGO_EXPORTER_PASSWORD
        - name: PROMETHEUS_PUSHGATEWAY
          valueFrom:
            configMapKeyRef:
              name: prometheus-pushgateway-map
              key: PROMETHEUS_PUSHGATEWAY
        ports:
          - containerPort: 5400
        resources:
            requests:
              cpu: '0.125'
              memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: mymicroservices
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
    - name: http-web
      protocol: TCP
      port: 5400
      targetPort: 5400
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: product-alerts
  namespace: observability
  labels:
    release: kube-prom-stack
    role: server-rules
spec:
  groups:
  - name: product.rules
    rules:
    - alert: product_down
      expr: absent(container_memory_usage_bytes{container="product"})
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: Product down
        description: Product container is down for more than 30 seconds.
    - alert: product_high_cpu
      expr: sum(rate(container_cpu_usage_seconds_total{container="product"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Product high CPU usage
        description: Product CPU usage is {{ humanize $value}}%.
    - alert: product_high_memory
      expr: sum(container_memory_usage_bytes{container="product"}) > 1200000000
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: Product high memory usage
        description: Product memory consumption is at {{ humanize $value}}.
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-svc
  namespace: observability
  labels:
    app: product
    release: kube-prom-stack
spec:  
  selector:
    matchLabels:
      app: product      
  endpoints:
    - port: http-web
      interval: 15s
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:                                                                                                                                                                                                                      
    matchNames:                                                                                                                                                                                                                           
    - mymicroservices
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-autoscaler
  namespace: mymicroservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-dpl
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: main-route
      target:
        type: Value
        value: 10k